DROP TABLE IF EXISTS clicks_agg;
DROP TABLE IF EXISTS link_rules;
DROP TYPE IF EXISTS device_type;
DROP TABLE IF EXISTS link_meta;
DROP TABLE IF EXISTS links;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS user_role;
DROP TABLE IF EXISTS tenants;
