api:
  image:
    repository: nghiadaulau/shortlink-api
    tag: v0.0.1
    pullPolicy: IfNotPresent
  replicaCount: 1

redirector:
  image:
    repository: nghiadaulau/shortlink-redirector
    tag: v0.0.1
    pullPolicy: IfNotPresent
  replicaCount: 1

collector:
  enabled: false
  image:
    repository: nghiadaulau/shortlink-collector
    tag: v0.0.1
    pullPolicy: IfNotPresent
  replicaCount: 1

ui:
  image:
    repository: nghiadaulau/shortlink-ui
    tag: v0.0.1
    pullPolicy: IfNotPresent

env:
  DATABASE_URL: "postgres://postgres:postgres@postgres:5432/shortlink?sslmode=disable"
  REDIS_ADDR: "redis:6379"
  JWT_SECRET: "changeme"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: shortlink.local
      paths:
        - path: /api
          pathType: Prefix
          service: shortlink-api
          port: 80
        - path: /
          pathType: Prefix
          service: redirector
          port: 80
    - host: ui.shortlink.local
      paths:
        - path: /
          pathType: Prefix
          service: shortlink-ui
          port: 80
  tls: []
